version: '3'
services:
  redis:
    container_name: redis
    hostname: redis:7.0.7
    image: redis:latest
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"